collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2267108673695475
  brandStrength: 0.09450637898407876
  lightness: 0.9310200230684131
  brandColors:
    - '#17182C'
    - '#613738'
    - '#C7B795'
    - '#7D6F6A'
    - '#FCFDDC'
  rhythmicContrast: 0.6540634927805513
typography_spectrum: 0.5009927724022418
layout_spectrum: 0
name: Brackish
